apiVersion: apps/v1
kind: Deployment
metadata:
  name: platml-frontend
  namespace: platml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platml-frontend
  template:
    metadata:
      labels:
        app: platml-frontend
    spec:
      containers:
      - name: platml-frontend
        image: gcr.io/graphic-perigee-456801-r0/platml-frontend:v4
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://35.224.58.29"
        - name: SERVE_URL
          value: "http://35.232.54.92"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: platml-frontend
  namespace: platml
spec:
  selector:
    app: platml-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer