apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platml-model-storage
  namespace: platml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-multizone
  resources:
    requests:
      storage: 2Gi