apiVersion: apps/v1
kind: Deployment
metadata:
  name: platml-serve
  namespace: platml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platml-serve
  template:
    metadata:
      labels:
        app: platml-serve
    spec:
      containers:
      - name: platml-serve
        image: gcr.io/graphic-perigee-456801-r0/platml-serve:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: model-storage
          mountPath: /app/model_storage
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: platml-model-storage
---
apiVersion: v1
kind: Service
metadata:
  name: platml-serve
  namespace: platml
spec:
  selector:
    app: platml-serve
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer