apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mlplat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api-service-account
      containers:
      - name: api
        image: gcr.io/graphic-perigee-456801-r0/api:v1
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mlplat
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: mlplat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
  namespace: mlplat
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-role-binding
  namespace: mlplat
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: mlplat
roleRef:
  kind: Role
  name: api-role
  apiGroup: rbac.authorization.k8s.io